openapi: 3.2.0
info:
  contact:
    email: stackit-iaas@mail.schwarz
    name: STACKIT IaaS Teams
    url: https://support.stackit.cloud/servicedesk
  description: This API is deprecated. It will be retired on 01.03.2027. Please use the STACKIT IaaS API V2 instead.
  termsOfService: https://stackit.de/en/imprint
  title: STACKIT IaaS Availability Zones API
  version: '1'
servers:
- url: https://iaas.api.{region}stackit.cloud
  variables:
    region:
      default: eu01.
      enum:
      - eu01.
tags:
- name: Availability Zones
paths:
  /v1/availability-zones:
    get:
      deprecated: true
      description: Get a list of all availability zones.
      operationId: ListAvailabilityZones
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilityZoneListResponse'
          description: Get a list of availability zones.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: List all availability zones
      x-stackit-authorization:
        disabled: true
      tags:
      - Availability Zones
components:
  responses:
    Forbidden:
      content:
        application/json:
          example:
            code: 403
            msg: Forbidden
          schema:
            $ref: '#/components/schemas/Error'
      description: A request which was forbidden.
    Unauthorized:
      content:
        application/json:
          example:
            code: 401
            msg: Unauthorized
          schema:
            $ref: '#/components/schemas/Error'
      description: A request which was not authorized.
    BadRequest:
      content:
        application/json:
          examples:
            InvalidAffinityGroupPolicy:
              value:
                code: 400
                msg: The affinity group policy is not supported
            InvalidBootDeviceSize:
              value:
                code: 400
                msg: boot device size is not valid or missing
            InvalidMachineType:
              value:
                code: 400
                msg: machine type is not valid
            InvalidParameter:
              value:
                code: 400
                msg: 'request body has an error: doesn''t match schema: Error at "/name": value must be a string'
            InvalidPublicKey:
              value:
                code: 400
                msg: invalid pubkey
            InvalidUUID:
              value:
                code: 400
                msg: invalid uuid
          schema:
            $ref: '#/components/schemas/Error'
      description: A bad request.
    InternalServerError:
      content:
        application/json:
          example:
            code: 500
            msg: internal server error
          schema:
            $ref: '#/components/schemas/Error'
      description: Internal Server Error, returns a 500 if something is broken on IaaS API Side.
    NotFound:
      content:
        application/json:
          examples:
            AreaNotFound:
              value:
                code: 404
                msg: area not found
            KeypairNotFound:
              value:
                code: 404
                msg: keypair not found
            NetworkNotFound:
              value:
                code: 404
                msg: network not found
            NetworkRangeNotFound:
              value:
                code: 404
                msg: network range not found
            OrganizationNotFound:
              value:
                code: 404
                msg: organization not found
            ProjectNotFound:
              value:
                code: 404
                msg: project not found
            RequestNotFound:
              value:
                code: 404
                msg: request not found
            RouteNotFound:
              value:
                code: 404
                msg: route not found
          schema:
            $ref: '#/components/schemas/Error'
      description: The object was not found.
  schemas:
    AvailabilityZoneListResponse:
      description: Availability Zone list response.
      properties:
        items:
          $ref: '#/components/schemas/AvailabilityZoneList'
      required:
      - items
      type: object
    Error:
      description: Error with HTTP error code and an error message.
      properties:
        code:
          example: 404
          format: int64
          type: integer
          x-stackit-logging: true
        msg:
          $ref: '#/components/schemas/errorMessage'
      required:
      - code
      - msg
      type: object
    errorMessage:
      description: An error message.
      example: Project not found
      type: string
    AvailabilityZoneList:
      description: A list of availability zones.
      items:
        $ref: '#/components/schemas/AvailabilityZone'
      type: array
    AvailabilityZone:
      description: Object that represents an availability zone.
      example: eu01-1
      type: string
